const twoSums = require('./two-sums')
const maxConsecutiveOnes = require('./max-consecutive-ones')
const longestSubstringWithoutRepeatingCharacters = require('./longest-substring-without-repeating-characters')
const threeSums = require('./three-sums')
const validParentheses = require('./valid-parentheses')
const validPalindrome = require('./valid-palindrome')
const winningCard = require('./winning-card')
const generateSentence = require('./generate-sentence')

twoSums()
maxConsecutiveOnes()
longestSubstringWithoutRepeatingCharacters()
threeSums()
validParentheses()
validPalindrome()
winningCard()
generateSentence()
