require('./two-pointers/')
const maxConsecutiveOnes = require('./max-consecutive-ones')
const longestSubstringWithoutRepeatingCharacters = require('./longest-substring-without-repeating-characters')
const threeSums = require('./three-sums')
const validParentheses = require('./valid-parentheses')
const validPalindrome = require('./valid-palindrome')
const winningCard = require('./winning-card')
const generateSentence = require('./generate-sentence')
const sortedSquared = require('./sorted-squared')
const findFirstNonRepeatingCharacterIndex = require('./find-first-non-repeating-character-index')
const splitString = require('./split-string')

maxConsecutiveOnes()
longestSubstringWithoutRepeatingCharacters()
threeSums()
validParentheses()
validPalindrome()
winningCard()
generateSentence()
sortedSquared()
findFirstNonRepeatingCharacterIndex()
splitString()
