const twoSums = require('./two-sums')
const maxConsecutivesOnes = require('./max-consecutives-ones')
const longestSubstringWithoutRepeatingCharacters = require('./longest-substring-without-repeating-characters')
const threeSums = require('./three-sums')
const validParentheses = require('./valid-parentheses')

twoSums()
maxConsecutivesOnes()
longestSubstringWithoutRepeatingCharacters()
threeSums()
validParentheses()
